baseurl: "https://ouce.opennms.eu/"
title: "OUCE 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-80485373-2"

params:
  # Conference info
  Name: "OUCE 2018"
  Description: "OpenNMS User Conference Europe"
  Date: "Oktober"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "To be defined"
  Address: "To be defined"
  City:  "Munich"
  State: "Bavaria"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    # - location
    - speakers
    - schedule
    # - partners
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Welcome"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Call for Paper"
    link: "/cfp/2018"

  # List of Sponsors
  # Sponsors:
  #   - name: "Hugo"
  #     logo: "/img/hugo.png"
  #     url: "http://gohugo.io"

  # List of Sponsors
  Sponsors:
    - name: "The OpenNMS Group"
      logo: "/img/opennms-logo.png"
      url: "https://www.opennms.com"
    - name: "NETHINKS GmbH"
      logo: "/img/nethinks-logo.jpg"
      url: "https://www.nethinks.com"

  Speakers:
    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      twitter: "https://twitter.com/jeffgdotorg"
    - name: "Ronny Trommer"
      photo: "/img/ronny-trommer.png"
      bio: "He has been working for more than 10 years in IT and has been using OpenNMS since 2004. He worked as a scientific assistant at the University of Applied Sciences in Fulda and wrote with his two friends Alexander Finger and Klaus Thielking-Riechert the German book about OpenNMS. He is also an elected member of the Order of the Green Polo since 2010 and was a Google Summer of Code mentor for the OpenNMS project."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      twitter: "https://twitter.com/indigo423"
      github: "https://github.com/indigo423"
      linkedin: "https://www.linkedin.com/in/ronnytrommer/"
      homepage: "https://blog.no42.org"

  # The entire schedule
  Schedule:
    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Supportability Roundtable"
        description: ""
        time: "TBD"
    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Single and Reduced Sign-On in OpenNMS"
        description: "This talk is about using advanced Sign-In technologies in OpenNMS"
        time: "TBD"
    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: " The HOE Stack: Helm + OpenNMS + Elasticsearch"
        description: "How to run OpenNMS with Helm in Grafana and Elasticsearch"
        time: "TBD"
    - name: "Ronny Trommer"
      photo: "/img/ronny-trommer.png"
      bio: "He has been working for more than 10 years in IT and has been using OpenNMS since 2004. He worked as a scientific assistant at the University of Applied Sciences in Fulda and wrote with his two friends Alexander Finger and Klaus Thielking-Riechert the German book about OpenNMS. He is also an elected member of the Order of the Green Polo since 2010 and was a Google Summer of Code mentor for the OpenNMS project."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Docker: Hello Ground!"
        description: "The Whale and the Bowl of Petunias"
        time: "TBD"
