baseurl: "https://ouce.opennms.eu/"
title: "OUCE 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-80485373-2"

params:
  # Conference info
  Name: "OUCE 2018"
  Description: "OpenNMS User Conference Europe"
  Date: "September 20 - 21, 2018"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Rilano Hotel"
  Address: "Rilano Hotel München, Domagkstr. 26"
  City:  "Munich"
  State: "Bavaria"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyBdXjIuucpDzKskIeAoOa9QtPz6XH9sJBo"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - tickets
    - location
    - speakers
    - schedule
    # - partners
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Welcome"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    tickets: "Tickets"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Call for Papers"
    link: "/cfp/2018"

  # List of Sponsors
  Sponsors:
    - name: "The OpenNMS Group"
      logo: "/img/opennms-logo.png"
      url: "https://www.opennms.com"
    - name: "NETHINKS GmbH"
      logo: "/img/nethinks-logo.jpg"
      url: "https://www.nethinks.com"

  Speakers:
    - name: "Tarus Balog"
      photo: "/img/tarus-balog.jpg"
      bio: "Tarus Balog has been involved in managing communications networks professionally since 1988, and unprofessionally since 1978 when he got his first computer - a TRS-80 from Radio Shack. Having worked as a network management consultant for many years, he was constantly frustrated in the lack of flexibility involved in commercial solutions from such companies as HP and IBM, as well as shocked by their high prices. Looking for a better solution, he turned to open source and joined the OpenNMS project in 2001 and become the principal administrator of the project in 2002. Since then he has managed not only to make a living working with free software, but the OpenNMS Group, the services company behind the project, has thrived. He is an outspoken evangelist for open source software and the communities it inspires."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, #1"
      twitter: "https://twitter.com/sortova"
      github:  "https://github.com/Sortova"
      linkedin: "https://www.linkedin.com/in/tarusbalog/"
      homepage: "https://www.adventuresinoss.com"
      gplus: "https://plus.google.com/+TarusBALOG"

    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      twitter: "https://twitter.com/jeffgdotorg"
      github:  "https://github.com/jeffgdotorg"
      linkedin: "https://www.linkedin.com/in/jgehlbach/"
      homepage: "https://jeffg.org/"
      gplus: "https://plus.google.com/u/0/+JeffGehlbach"
      keybase: "https://keybase.io/jeffg"

    - name: "Jesse White"
      photo: /img/jesse-white.jpg
      bio: CTO of The OpenNMS Group, Inc.
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      github: "https://github.com/j-white"
      linkedin: "https://www.linkedin.com/in/jwhite1/"
      homepage: "https://www.jessewhite.ca"

    - name: "Jessica Hustace"
      photo: "/img/jessica-hustace.jpg"
      bio: Graphic Designer + Accounts at The OpenNMS Group, Inc.
      company: "The OpenNMS Group, Inc."
      link:
          href: "https://www.opennms.org"
          text: "OpenNMS"
      linkedin: "https://www.linkedin.com/in/jessica-hustace-2ab15429/"

    - name: "Craig Gallen"
      photo: /img/craig-gallen.jpg
      bio: Craig Gallen is a committer to OpenNMS, supports OpenNMS users in UK and Ireland and is an Associate Lecturer at Solent University in the UK.
      company: "entimoss limited (OpenNMS UK)"
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      github: "https://github.com/gallenc"
      linkedin: "https://www.linkedin.com/in/craig-gallen-a4332a/"
      homepage: "http://entimoss.myzen.co.uk"

    - name: "Benjamin Reed"
      photo: "/img/benjamin-reed.jpg"
      bio: CIO of The OpenNMS Group, Inc. Software Developer
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      github: "https://github.com/RangerRick"
      linkedin: "https://www.linkedin.com/in/rangerrick/"
      twitter: https://twitter.com/rangerrick
      keybase: https://keybase.io/rangerrick
      gplus: https://plus.google.com/u/0/+BenjaminReed

#    - name: "Patrick Kremser"
#      photo: "/img/patrick-kremser.jpg"
#      bio: NETHINKS GmbH
#      company: "NETHINKS GmbH"
#      link:
#        href: "https://www.nethinks.com"
#        text: ""

#    - name: "Mark Heumüller"
#      photo: "/img/mark-heumueller.jpg"
#      bio: NETHINKS GmbH
#      company: "NETHINKS GmbH"
#      link:
#        href: "https://www.nethinks.com"
#        text: ""

    - name: "Ronny Trommer"
      photo: "/img/ronny-trommer.png"
      bio: "He has been working for more than 10 years in IT and has been using OpenNMS since 2004. He worked as a scientific assistant at the University of Applied Sciences in Fulda and wrote with his two friends Alexander Finger and Klaus Thielking-Riechert the German book about OpenNMS. He is also an elected member of the Order of the Green Polo since 2010 and was a Google Summer of Code mentor for the OpenNMS project."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      twitter: "https://twitter.com/indigo423"
      github: "https://github.com/indigo423"
      linkedin: "https://www.linkedin.com/in/ronnytrommer/"
      homepage: "https://blog.no42.org"
      gplus: "https://plus.google.com/102627149457811467262"

  # The entire schedule
  Schedule:
    - name: "Tarus Balog"
      photo: /img/tarus-balog.jpg
      bio: Founder of The OpenNMS Group, Inc.
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, #1"
      presentation:
        title: "Keynote"
        description: "OpenNMS now and the future."
        time: "TBD"

    - name: "Jesse White"
      photo: /img/jesse-white.jpg
      bio: CTO of The OpenNMS Group, Inc.
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "OpenNMS Integration Patterns"
        description: "Interested in forwarding events to Kafka? Sending alarms via AQMP? Transmitting performance data via Protobuf over TCP? We'll look at these integration points, and some of the other options for integrating OpenNMS with other tools in your infrastructure."
        time: "TBD"

    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Supportability Roundtable"
        description: ""
        time: "TBD"

    - name: "Benjamin Reed"
      photo: "/img/benjamin-reed.jpg"
      bio: "CIO at The OpenNMS Group, Inc. - Software Developer"
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Modern JavaScript in OpenNMS"
        description: "Working with JavaScript in OpenNMS Horizon 22 and beyond. I will discuss the recent work I did to refactor and modernize the OpenNMS JavaScript codebase, as well as how to integrate new JavaScript code into OpenNMS."
        time: "TBD"

    - name: "Craig Gallen"
      photo: /img/craig-gallen.jpg
      bio: Solutions Consultant
      company: "entimoss limited (OpenNMS UK)"
      link:
        href: "http://entimoss.myzen.co.uk"
        text: "OpenNMS, OGP"
      presentation:
        title: "OpenNMS and MQTT IoT for Pollution Monitoring"
        description: "This talk will discuss an MQTT plugin which allows OpenNMS to receive MQTT Performance and Event messages from Raspberry Pi devices."
        time: "TBD"

    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Single and Reduced Sign-On in OpenNMS"
        description: "This talk is about using advanced Sign-In technologies in OpenNMS"
        time: "TBD"

    - name: "Jessica Hustace"
      photo: "/img/jessica-hustace.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "OpenNMS Community Roundtable"
        description: "Reflection upon current and recent community activities followed by roundtable of suggestions, sharing stories, and questions. What has the OpenNMS community been up to? We've been busy going to lots of conferences, eating poutine, drinking mate, and solving problems. Learn about the various places one can engage with the OpenNMS community online (in the tubes) or in person (in the meats). What do those terms mean? Where did they come from? Find out! Meet some of our more active community members and reflect on some of the fun memories we've made together in the last year! Want to join in the fun but are feeling unsure about where to begin? Feel free to ask here or submit a question anonymously. Also, please bring suggestions and constructive criticism regarding our community organization!"
        time: "TBD"

    - name: "Jeff Gehlbach"
      photo: "/img/jeff-gehlbach.jpg"
      bio: "Jeff has worked with free software since the mid-1990s and has practiced the discipline of large-scale network management since 2000. His current role as Director of Applied Innovation at The OpenNMS Group lets him continue both these pursuits, and even affords him to write the occasional line or two of code."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "The HOE Stack: Helm + OpenNMS + Elasticsearch"
        description: "How to run OpenNMS with Helm in Grafana and Elasticsearch"
        time: "TBD"

    - name: "Ronny Trommer"
      photo: "/img/ronny-trommer.png"
      bio: "He has been working for more than 10 years in IT and has been using OpenNMS since 2004. He worked as a scientific assistant at the University of Applied Sciences in Fulda and wrote with his two friends Alexander Finger and Klaus Thielking-Riechert the German book about OpenNMS. He is also an elected member of the Order of the Green Polo since 2010 and was a Google Summer of Code mentor for the OpenNMS project."
      company: "The OpenNMS Group, Inc."
      link:
        href: "https://www.opennms.org"
        text: "OpenNMS, OGP"
      presentation:
        title: "Docker: Hello Ground!"
        description: "The Whale and the Bowl of Petunias. While maintaining the Horizon and Minion Docker Images on DockerHub, I want to share some experience what happens if you run a legacy application like OpenNMS Horizon and Minions in a container environment like Docker."
        time: "TBD"
